branches:
  only: [FISCO-BCOS/web3sdk-748-origin]
jobs:
  fast_finish: true
  include:
  - {language: java, jdk: openjdk8, os: linux, dist: xenial, sudo: required}
  - {language: java, jdk: openjdk11, os: linux, dist: xenial, sudo: required}
  - {language: java, jdk: openjdk14, os: linux, dist: xenial, sudo: required}
  - {language: java, jdk: oraclejdk11, os: linux, dist: xenial, sudo: required}
  - {language: java, jdk: oraclejdk14, os: linux, dist: xenial, sudo: required}
  - {language: java, jdk: openjdk8, os: linux, dist: bionic, sudo: required}
  - {language: java, jdk: openjdk11, os: linux, dist: bionic, sudo: required}
  - {language: java, jdk: openjdk14, os: linux, dist: bionic, sudo: required}
  - {language: java, jdk: oraclejdk11, os: linux, dist: bionic, sudo: required}
  - {language: java, jdk: oraclejdk14, os: linux, dist: bionic, sudo: required}
addons:
  apt:
    packages: [openssl, libssl-dev]
before_cache: [rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock, rm -fr $HOME/.gradle/caches/*/plugin-resolution/]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
script: |
  bash .ci/ci_check.sh
