sudo: required
addons:
  ssh_known_hosts: [demo.swellrt.org, assange.fdi.ucm.es]
language: java
jdk: oraclejdk8
services: [docker]
script: [./gradlew clean jar prodWeb test]
after_success: [.travis/deploy.sh]
branches:
  only: [SwellRT/swellrt-249-origin]
