language: android
sudo: false
git:
  depth: 3 #将git depth设置相对小的值,加快构建速度
jdk:
  - oraclejdk8 #lambda表达式支持,如果工程中使用了rxJava等类库时添加
branches:
  - dxsdyhm/AlarmAndJob-4-GRADLE_FORK_TEST
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-android-support

script:
  - "./gradlew assembleDebug"

script:
    - "./gradlew assembleDebug"
    - fir login 58e870036c7798894efce2037c563ab6 #fir账号的Token
    - fir me #打印身份信息,验证是否登录成功
    - find ./ -name app-debug.apk
    - fir p ./app/build/outputs/apk/app-debug.apk #自动发布应用至fir内测平台

before_install:
    - chmod +x gradlew
    - gem install fir-cli #安装fir命令行客户端

notifications:
  webhooks:https://oapi.dingtalk.com/robot/send?access_token=a89c1543026b69693022764f0543fac45497e12bb393270e5f4c987a7376d286
