language: java
jdk: [openjdk8]
before_cache: [rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock, rm -fr $HOME/.gradle/caches/*/plugin-resolution/]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
branches:
  only: [alex-shpak/rx-jersey-22-GRADLE_REPORT_GENERATION]
