language: android
jdk: oraclejdk8
android:
  components: [platform-tools, tools, build-tools-26.0.2, android-22, extra]
script: ./travis/build.sh
branches:
  only: [WebBluetoothCG/ble-test-peripheral-android-103-GRADLE_INCREMENTAL_COMPILATION]
