os: linux
dist: bionic
addons:
  apt:
    packages: [thrift-compiler]
language: java
jdk: [openjdk8]
script: ['./gradlew -Djava.security.egd=file:/dev/urandom warp10:pack']
notifications: {email: false}
branches:
  only: [senx/warp10-platform-1041-GRADLE_COMPILER_DAEMON]
