language: java
jdk: [oraclejdk8]
branches:
  only: [AndreasFagschlunger/O2Xfs-91-GRADLE_COMPILER_DAEMON]
before_install: [chmod +x gradlew]
script: [./gradlew clean build -x test --continue --stacktrace]
