sudo: false
dist: trusty
branches:
  only: [cyclestreets/android-494-GRADLE_REPORT_GENERATION]
git: {depth: false}
language: android
addons:
  apt:
    packages: [openjdk-9-jdk, openjdk-11-jdk]
env:
  global:
  - compileSdkVersion=30
  - minSdkVersion=23
  - targetSdkVersion=29
  - toolsVersion=30.0.3
  - JAVA8_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - JAVA9_HOME=/usr/lib/jvm/java-9-openjdk-amd64
  - JAVA11_HOME=/usr/lib/jvm/java-11-openjdk-amd64
  - {secure: LipL0wPv0uQrKitaeGxCpoQsx5sl/Pg/DtQv4S7Bi52DxfArgvD2hPB0TWgkgYGJPfENHLEyqg+H+/v2nON3IXY+cnsd+TW+P1T03/52D56ieSKGVtVtSYUOZUgoyxIIvRZWFh/UNg+AmZIjOCTJDLitBTUxD8kWux8NjhIqZow=}
android:
  components: [tools, platform-tools, tools, 'build-tools-${toolsVersion}', 'android-${compileSdkVersion}']
before_install: [./ciLicense.sh, sudo pip install requests, touch $HOME/.android/repositories.cfg,
  jdk_switcher use openjdk8, yes | sdkmanager "platforms;android-30", yes | sdkmanager
    "build-tools;30.0.3"]
install: [ls -l /usr/lib/jvm/, ./checkPoiTypeIcons.sh, 'JAVA_HOME=${JAVA9_HOME} ./gradlew
    build -Dorg.gradle.java.home=${JAVA9_HOME} -x lint']
script: [./ciPublish.sh]
