language: android
sudo: required
dist: trusty
env:
  global: [EMULATOR_API_LEVEL=19, ANDROID_ABI=armeabi-v7a, ADB_INSTALL_TIMEOUT=20,
    'AVD_DEBUG=''init,avd_config,nand_limits,keys,adb,adbserver,adbclient''']
jdk: [oraclejdk8]
android:
  components: [tools, platform-tools, tools, build-tools-28.0.3, android-$EMULATOR_API_LEVEL,
    android-23, android-26, extra-google-m2repository, extra-android-m2repository,
    extra-android-support, extra-google-google_play_services, sys-img-$ANDROID_ABI-google_apis-$EMULATOR_API_LEVEL]
  licenses: [android-sdk-license-.+, google-gdk-license-.+]
before_install: [chmod +x gradlew, touch $HOME/.android/repositories.cfg, yes | sdkmanager
    "platforms;android-29"]
before_script: [android list targets]
script: [nice ./gradlew test -PdisablePreDex, ./gradlew assembleRelease]
after_failure: [cat app/build/reports/tests/testDebugUnitTest/classes/*, cat app/build/reports/tests/testReleaseUnitTest/classes/*]
branches:
  only: [NightscoutFoundation/xDrip-1875-GRADLE_COMPILER_DAEMON]
