language: android
android:
  components: [tools, build-tools-29.0.2, android-29]
jdk: oraclejdk8
script: [./gradlew build]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
branches:
  only: [jberkel/sms-backup-plus-1072-GRADLE_REPORT_GENERATION]
