language: java
env:
  global:
  - {secure: IWTGpN+lL2X+0FdpdPF7oBPxI9aE6XTnRrT/xBiUQBvcTcex1I8ZLUmjTSabH0yIG2Vl854EuHwd8TGbRwyTArk4xfn2m+P4iqnNXZej3ywMNMGlrS/jzvKVHmf+/7vuxmXtfo0rPk1hRudW5qASLicUf9Rr/o4ymk46E/E2eQ0=}
  - {secure: OB8GvnzyIWK2IwLzKnBquFr7L8k3vnJHCAHZSUuD7Me3t9vBjvc6tv77C2E0SqNiPi8QE/uxq+25rthL2sp+p7Xino3JRKcWxA2zSKA/1BfK0U5sxe3v1LL2fQHuKvfHr3KYFju5O534UEioGvTdAsUg6+MDsq1OJuD6rOeluGw=}
script: gradle build
jdk: [oraclejdk8]
install: gradle assemble --stacktrace
after_success: [test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master"
    && gradle uploadArchives]
branches:
  only: [ClearVolume/clearvolume-83-origin]
