language: java
install: true
jdk: oraclejdk8
env:
  matrix: [TERM=dumb]
before_script: [./gradlew --version]
script: ./gradlew build
after_success: [./gradlew jacocoTestReport coveralls]
branches:
  only: [http-builder-ng/http-builder-ng-234-GRADLE_PARALLEL_TEST]
