language: java
jdk: [openjdk8]
branches:
  only: [jojoldu/springboot-webservice-2-GRADLE_FORK_TEST]
cache:
  directories: [$HOME/.m2/repository, $HOME/.gradle]
script: ./gradlew clean build
before_deploy: [zip -r springboot-webservice *, mkdir -p deploy, mv springboot-webservice.zip
    deploy/springboot-webservice.zip]
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: springboot-webservice-deploy
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  local_dir: deploy
  wait-until-deployed: true
  true: {repo: jojoldu/springboot-webservice, branch: master}
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: springboot-webservice-deploy
  key: springboot-webservice.zip
  bundle_type: zip
  application: springboot-webservice
  deployment_group: springboot-webservice-group
  region: ap-northeast-2
  wait-until-deployed: true
  true: {repo: jojoldu/springboot-webservice, branch: master}
notifications:
  email:
    recipients: [jojoldu@gmail.com]
