language: java
jdk: [oraclejdk8]
before_install: ./gradlew assemble -x signArchives
install: echo "install"
script: ./gradlew clean check -x signArchives
branches:
  only: [chbatey/kafka-unit-74-GRADLE_INCREMENTAL_COMPILATION]
