language: android
jdk: [oraclejdk8]
android:
  components: [tools, platform-tools, build-tools-25.0.0, android-25, extra-android-m2repository]
before_install: [chmod +x gradlew]
script: [./gradlew clean build --info]
branches:
  only: [Scalified/fab-48-origin]
