language: android
jdk: oraclejdk8
before_install: [yes | sdkmanager "platforms;android-29", chmod +x gradlew]
env:
  global: [ANDROID_API_LEVEL=29, ANDROID_BUILD_TOOLS_VERSION=29.0.2, TRAVIS_SECURE_ENV_VARS=true]
android:
  components: [tools, platform-tools, build-tools-$ANDROID_BUILD_TOOLS_VERSION, extra-android-m2repository,
    extra-google-android-support, android-$ANDROID_API_LEVEL]
  licenses: [.+]
script: [./gradlew clean, ./gradlew assembleDebug]
branches:
  only: [alidili/RecyclerViewHelper-4-origin]
