language: android
android:
  components: [build-tools-21.1.1, android-21, extra-android-m2repository]
script: ./gradlew assembleFossDebug JMPDCommJava:Build
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
branches:
  only: [abarisain/dmix-876-origin]
