version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - java -version
  - gradlew.bat --version
build_script:
  - gradlew.bat -u -i assemble
test_script:
  - gradlew.bat -u -i -S build -x test
