branches:
  only:
    - master
    - development

skip_tags: true

install:
- "gradlew.bat build"
- "gradlew.bat generateExternalPatches"
- "gradlew.bat build"

build_script:
- "gradlew.bat verify"

artifacts:
- path: build\libs\*.*
