version: 2.0

jobs:
  build:
    docker:
      - image: typelead/eta:latest

    steps:
      - checkout

      - restore_cache:
          key: gradle-eta-v075-

      - run: ./gradlew pTML

      - run: etlas update

      - run: ./tests/test.sh

      - save_cache:
          key: gradle-eta-v075-{{ epoch }}
          paths:
            - "~/.etlas/config"
            - "~/.etlas/packages"
            - "~/.etlas/tools"
            - "~/.gradle/caches/transforms-1"
            - "~/.gradle/caches/modules-2"
            - "~/.gradle/caches/jars-3"
            - "~/.gradle/caches/4.7/generated-gradle-jars"
            - "~/.gradle/wrapper"

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
